### ISSUE TITLE
Do we have option to turn on/off this feature?

### ISSUE THREAD

**Issue by Sondt88** [ElkanRoelen/behatformatter#8]
Dear Elkan Roelen,

Do we have an option to turn on/off the report in behat.yml file ?
Sometime, I would like to turn off and check issue from command line.

Thank you so much for great extension.

**Comment by Florian-Merle** [comment]
Hi,

You can have both a the html report and the command line report. Just add the node "pretty" in your behat.yml file, just like that:

```
  formatters:
    pretty: ~
    html:
      output_path: %paths.base%/...
```

When you don't configure any formatter, behat will use "pretty" by default. It's the one that prints the report in the CLI.
